server:
  port: 8080
spring:
  application:
    #应用名称：可选项
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: lc908835895
  web:
    resources:
      #默认解析的静态资源路径
      static-locations: ["classpath:/templates/"]

#  shardingsphere:
#    datasource:
#      names:
#        # 主 从 库的命名
#        master1 slave1
#      master1:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.22.15:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#        username: root
#        password: lc908835895
#      slave1:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.22.17:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#        username: root
#        password: lc908835895
#    masterslave:
#      #读写分离配置，负载均衡策略
#      load-balance-algorithm-type: round_robin
#      #最终数据源名称
#      name: dataSource
#      #主库数据源名称
#      master-data-source-name: master1
#      #从库数据源名称列表，多个从库逗号分隔
#      slave-data-source-names: slave1
#    props:
#      sql:
#        #开启sql显示，默认false
#        show: true
##      允许bean定义覆盖
# main:
#   allow-bean-definition-overriding: true


#  mvc:
#    static-path-pattern: "/backend/**"
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    #开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #主键的生成策略，这里选用的是雪花算法
      id-type: ASSIGN_ID
reggie:
 path: "C:\\Users\\ASUS\\Desktop\\photo"